service: mic-db

frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:DeleteObject'
            - 's3:DeleteObjectVersion'
          Resource: 
            - "arn:aws:s3:::*"
  environment:
    prefixApp: MIC-DB
    STAGE: ${self:provider.stage}
  

    